version: '3.7'

services:
  frontend:
    container_name: algoscalc-front.local
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    env_file:
      - .env.local