version: '3.7'

services:
  frontend:
    container_name: algoscalc-front.local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    env_file:
      - .env.local
    restart: always
