version: '3.7'

services:

  front_prod:
    container_name: FrontProd
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      nginx_net1:

networks:
  nginx_net1:
    external:
      name: nginx-net
