version: '3.7'

services:

  front_test:
    container_name: FrontTest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      nginx_net1:

networks:
  nginx_net1:
    external:
      name: nginx-net
