name: "CI CD actions"
on:
  push:
    tags:
      - 'v*'
    branches:
      - Test
      - Prod
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - Test
      - Prod
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'

permissions:
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_CONTAINER_NAME: FrontendTest

jobs:
  sonarcloud:
    name: SonarCloud code analyze
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/Test'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the version
        id: get_short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_ENVIRONMENT: "staging"
          envkey_REACT_APP_VERSION: ${{ steps.get_short_sha.outputs.SHORT_SHA }}
          file_name: .env
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test 
  deploy-test:
    name: Test deploy
    runs-on: ubuntu-latest
    needs: build-test
    if: needs.build-test.result == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SANDBOX_HOST }}
          username: ${{ secrets.SANDBOX_USER }}
          key: ${{ secrets.SANDBOX_KEY }}
          port: ${{ secrets.SANDBOX_PORT }}
          script: |
            docker logout;
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test;
            docker rm -f ${{ env.TEST_CONTAINER_NAME }} || true;
            docker run -d \
              --restart=always \
              --name ${{ env.TEST_CONTAINER_NAME }} \
              --network ${{ secrets.SANDBOX_NETWORK }} \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test;
  prod_deploy:
    name: Deploy Front Prod
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: executing remote ssh commands
      uses: fjogeleit/http-request-action@v1.16.1
      with:
        url: ${{ secrets.URL_WEBHOOK_PROD }}
        method: 'POST'