name: "OMMAT CiCd Prod"
on:
  pull_request:
    branches: ["Prod"]
    
jobs:
  deploy:
    name: Deploy Front Prod
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: fjogeleit/http-request-action@v1.16.1
      with:
        url: ${{ secrets.URL_WEBHOOK_PROD }}
        method: 'POST'
