name: "OMMAT CiCd"
on:
  push:
    branches: ["Test"]
  pull_request:
    branches: ["Test"]
    
jobs:
  deploy:
    name: Deploy Front Test
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: fjogeleit/http-request-action@v1.16.1
      with:
        url: ${{ secrets.URL_WEBHOOK_TEST }}
        method: 'POST'
