name: Run Front

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set image name
        id: vars
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '/' '-' | tr -cd '[:alnum:]-')
          COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)
          IMAGE_NAME="${BRANCH_NAME}-${COMMIT_HASH}"
          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Choosing free port
        id: choose-port
        run: |
          for port in $(seq 8081 8200); do
            if ! ss -Htan | awk '{print $4}' | grep -q ":$port\$"; then
              PORT=$port
              break
            fi
          done
          IP=$(curl -s ifconfig.me)

          echo "Chosen port: $PORT"
          echo "External IP: $IP"

          echo "port=$PORT" >> "$GITHUB_OUTPUT"
          echo "ip=$IP" >> "$GITHUB_OUTPUT"

      - name: Build and Run via Docker Compose
        run: |
          export FRONTEND_PORT=${{ steps.choose-port.outputs.port }}
          docker compose build
          docker compose up -d

      - name: Show IP
        run: echo "IP http://${{ steps.choose-port.outputs.ip }}:${{ steps.choose-port.outputs.port }}"
