name: Run Front

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set image name
        id: vars
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '/' '-' | tr -cd '[:alnum:]-')
          COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)
          IMAGE_NAME="${BRANCH_NAME}-${COMMIT_HASH}"
          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.vars.outputs.image }} .

      - name: Run container
        id: run
        run: |
          docker run -d --name=${{ steps.vars.outputs.image }} ${{ steps.vars.outputs.image }}

      - name: Show IP
        run: echo "Контейнер с фронтовой частью запущен"
